# Generated by Django 4.1.6 on 2023-08-09 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_barcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ratings", "0003_ratings_phoneid_alter_ratings_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ratings",
            unique_together={("product", "phoneId"), ("product", "user")},
        ),
        migrations.AddField(
            model_name="ratings",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
