# Generated by Django 4.1.6 on 2023-08-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0004_alter_ratings_unique_together_ratings_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratings",
            name="rating",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
